ManagerDeviceMenu: generate when SelectedDevice is missing
blueman-project/blueman pull request #1995
Opened 2022-12-31 18:15 UTC by infirit

2023-01-01 07:01 UTC, cschramm requested changes

2023-01-01 07:01 UTC, cschramm commented on blueman/gui/manager/ManagerDeviceMenu.py
>              if not hasattr(inst, "SelectedDevice"):
I think this condition should be added to the next `if` with `or` to a) show the log message and b) avoid generating twice.

2023-01-01 20:42 UTC, infirit commented
Finally got to the core of the problem, not having a row selected. As long as this is true everything else just works ™. Do you want me to open a PR with just the revert and the fix?

2023-01-02 06:44 UTC, cschramm approved these changes
Looks good like it is. :+1:

2023-01-02 16:36 UTC, merged